#ifndef STATE_MANAGER_EVENT_H
#define STATE_MANAGER_EVENT_H

#include "esp_event.h"

ESP_EVENT_DECLARE_BASE(STATE_MANAGER_EVENT);

enum {
    STATE_MANAGER_EVENT_UPDATE,
};

#endif // STATE_MANAGER_EVENT_H